# -*- coding: utf-8 -*-

"""
Startup bootstrap for hosts without shell access (e.g. Render free).

Runs from ``start.sh`` when ``SEED_ON_START=true``. It is deliberately
idempotent and conservative:

* seeds only when the destinations table is empty, so a restart can
  never duplicate rows or overwrite edited data;
* promotes ``ADMIN_EMAIL`` to admin if that user already exists - it
  never creates an account or sets a password, because provisioning
  credentials from an environment variable would be a bad idea;
* never raises: a bootstrap problem must not stop the web service
  from starting.

Run manually with:  python3 -m app.db.bootstrap
"""

from __future__ import annotations

import logging
import os
import sys

logging.basicConfig(level=logging.INFO, format="[bootstrap] %(message)s")
logger = logging.getLogger(__name__)


def _truthy(value: str) -> bool:
    return str(value).strip().lower() in ("1", "true", "yes", "on")


CORE_TABLES = ("users", "destinations", "hotel_offer_requests",
               "customer_offers", "payments")


def ensure_schema() -> None:
    """Create any missing tables, then mark Alembic as current.

    The autogenerated baseline was produced against a database that
    already contained the original tables, so on a brand-new database
    it creates almost nothing and later migrations fail on missing
    foreign-key targets. Creating the schema straight from the models
    is authoritative and idempotent; stamping head afterwards keeps
    future migrations working normally.
    """
    from sqlalchemy import inspect

    from app.db.database import engine
    from app.db.models import Base

    try:
        existing = set(inspect(engine).get_table_names())
    except Exception as exc:
        logger.warning("Could not inspect the database: %s", exc)
        return

    missing = [t for t in CORE_TABLES if t not in existing]
    if not missing:
        logger.info("Schema present (%d tables)", len(existing))
        return

    logger.info("Missing tables %s - creating schema from models",
                ", ".join(missing))
    try:
        Base.metadata.create_all(bind=engine)
    except Exception as exc:
        logger.warning("create_all failed: %s", exc)
        return

    created = set(inspect(engine).get_table_names())
    logger.info("Schema created: %d tables", len(created))

    # Tell Alembic the database is at head so later upgrades are clean.
    try:
        from alembic import command
        from alembic.config import Config

        cfg = Config("alembic.ini")
        command.stamp(cfg, "head")
        logger.info("Alembic stamped at head")
    except Exception as exc:
        logger.warning("Could not stamp alembic head: %s", exc)


def destinations_count() -> int:
    from app.db.database import SessionLocal
    from app.db.models import Destination

    session = SessionLocal()
    try:
        return session.query(Destination).count()
    finally:
        session.close()


def seed_if_empty() -> None:
    """Populate destinations only when there are none."""
    try:
        existing = destinations_count()
    except Exception as exc:
        logger.warning("Could not count destinations: %s", exc)
        return

    if existing:
        logger.info("%d destinations already present - not seeding",
                    existing)
        return

    # Note: seed() clears the destinations table first, which is
    # exactly why this only ever runs when the table is empty.
    logger.info("Destinations table is empty - seeding")
    try:
        from app.db import seed as seed_module
    except Exception as exc:
        logger.warning("Seed module unavailable: %s", exc)
        return

    try:
        entry = None
        for name in ("seed", "main", "run", "seed_database"):
            entry = getattr(seed_module, name, None)
            if callable(entry):
                entry()
                break
        else:
            # Importing the module is itself the seeding step in some
            # layouts; the import above already ran it.
            logger.info("Seed module executed on import")
        logger.info("Seeding finished: %d destinations",
                    destinations_count())
    except Exception as exc:
        logger.warning("Seeding failed: %s", exc)


def promote_admin() -> None:
    """Grant admin to ADMIN_EMAIL if that account exists already."""
    email = os.getenv("ADMIN_EMAIL", "").strip().lower()
    if not email:
        return
    try:
        from app.db.database import SessionLocal
        from app.db.models import User

        session = SessionLocal()
        try:
            user = (session.query(User)
                    .filter(User.email == email).one_or_none())
            if user is None:
                logger.info(
                    "ADMIN_EMAIL %s has no account yet - register on "
                    "the site, then restart to be promoted", email)
                return
            if user.is_admin:
                logger.info("%s is already an admin", email)
                return
            user.is_admin = True
            session.commit()
            logger.info("Promoted %s to admin", email)
        finally:
            session.close()
    except Exception as exc:
        logger.warning("Admin promotion skipped: %s", exc)


def main() -> int:
    # Schema creation always runs: a missing table is a broken
    # deployment, not an optional convenience. Only the data seeding
    # is gated behind SEED_ON_START.
    ensure_schema()
    if _truthy(os.getenv("SEED_ON_START", "")):
        seed_if_empty()
    else:
        logger.info("SEED_ON_START not set - skipping demo seeding")
    promote_admin()
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except Exception as exc:  # never block startup
        logger.warning("Bootstrap aborted: %s", exc)
        sys.exit(0)
