"""agency: roles, clients, quotes, bookings, cash

Revision ID: 189997f9aa1f
Revises: b9db6b562534
Create Date: 2026-10-05 15:40:03.668704
"""

from alembic import op
import sqlalchemy as sa


revision = '189997f9aa1f'
down_revision = 'b9db6b562534'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
