"""baseline

Revision ID: 59487d2f0749
Revises: 
Create Date: 2026-07-30 17:07:56.948430
"""

from alembic import op
import sqlalchemy as sa


revision = '59487d2f0749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
