"""customer role default and notification link

Revision ID: 71b7088d31c5
Revises: 52d10d9581d1
Create Date: 2026-10-09 15:55:12.431312
"""

from alembic import op
import sqlalchemy as sa


revision = '71b7088d31c5'
down_revision = '52d10d9581d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('link', sa.String(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'link')
    # ### end Alembic commands ###
