"""hotel acquisition

Revision ID: b9db6b562534
Revises: 59487d2f0749
Create Date: 2026-08-12 21:05:57.345000
"""

from alembic import op
import sqlalchemy as sa


revision = 'b9db6b562534'
down_revision = '59487d2f0749'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hotel_providers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rate_limit_note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('search_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('session_hash', sa.String(length=64), nullable=True),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_search_events_event_created', 'search_events', ['event', 'created_at'], unique=False)
    op.create_table('hotel_offer_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_name', sa.String(length=160), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=False),
    sa.Column('customer_phone', sa.String(length=60), nullable=True),
    sa.Column('destination', sa.String(length=160), nullable=True),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('hotel_name', sa.String(length=200), nullable=True),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(length=200), nullable=True),
    sa.Column('meal_plan', sa.String(length=40), nullable=True),
    sa.Column('current_provider', sa.String(length=80), nullable=True),
    sa.Column('competitor_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('competitor_url', sa.Text(), nullable=True),
    sa.Column('customer_message', sa.Text(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('offer_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_page', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotel_offer_requests_status_created', 'hotel_offer_requests', ['status', 'created_at'], unique=False)
    op.create_table('hotel_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('supplier', sa.String(length=40), nullable=False),
    sa.Column('room_id', sa.String(length=120), nullable=True),
    sa.Column('room_name', sa.String(length=200), nullable=True),
    sa.Column('board_type', sa.String(length=40), nullable=True),
    sa.Column('occupancy', sa.Integer(), nullable=False),
    sa.Column('check_in', sa.String(length=10), nullable=False),
    sa.Column('check_out', sa.String(length=10), nullable=False),
    sa.Column('nights', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('base_price', sa.Float(), nullable=True),
    sa.Column('taxes', sa.Float(), nullable=True),
    sa.Column('fees', sa.Float(), nullable=True),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('cancellation_policy', sa.String(length=200), nullable=True),
    sa.Column('refundable', sa.Boolean(), nullable=True),
    sa.Column('availability', sa.Boolean(), nullable=False),
    sa.Column('deep_link', sa.Text(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotel_offers_expires', 'hotel_offers', ['expires_at'], unique=False)
    op.create_index('ix_hotel_offers_lookup', 'hotel_offers', ['hotel_id', 'check_in', 'check_out', 'occupancy'], unique=False)
    op.create_table('hotel_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('max_occupancy', sa.Integer(), nullable=True),
    sa.Column('bed_type', sa.String(length=80), nullable=True),
    sa.Column('size_sqm', sa.Float(), nullable=True),
    sa.Column('amenities', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hotel_rooms_hotel_id', 'hotel_rooms', ['hotel_id'], unique=False)
    op.create_table('customer_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('hotel_name', sa.String(length=200), nullable=False),
    sa.Column('room_description', sa.String(length=250), nullable=True),
    sa.Column('board_type', sa.String(length=40), nullable=True),
    sa.Column('check_in', sa.String(length=10), nullable=True),
    sa.Column('check_out', sa.String(length=10), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('rooms', sa.Integer(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('cancellation_policy', sa.String(length=250), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('our_price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['hotel_offer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index('ix_customer_offers_request', 'customer_offers', ['request_id'], unique=False)
    op.create_table('competitor_comparisons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hotel_id', sa.Integer(), nullable=True),
    sa.Column('our_offer_id', sa.Integer(), nullable=True),
    sa.Column('competitor', sa.String(length=80), nullable=False),
    sa.Column('competitor_price', sa.Float(), nullable=False),
    sa.Column('competitor_currency', sa.String(length=3), nullable=False),
    sa.Column('competitor_room', sa.String(length=200), nullable=True),
    sa.Column('competitor_board', sa.String(length=40), nullable=True),
    sa.Column('competitor_cancellation', sa.String(length=200), nullable=True),
    sa.Column('competitor_taxes', sa.Float(), nullable=True),
    sa.Column('competitor_total', sa.Float(), nullable=False),
    sa.Column('comparison_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['hotel_id'], ['hotels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['our_offer_id'], ['customer_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('to_email', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('kind', sa.String(length=50), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['customer_offers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['request_id'], ['hotel_offer_requests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_email_log_created', 'email_log', ['created_at'], unique=False)
    op.create_table('offer_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=50), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['customer_offers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['request_id'], ['hotel_offer_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_offer_events_offer', 'offer_events', ['offer_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=200), nullable=True),
    sa.Column('provider_session_id', sa.String(length=200), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['customer_offers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_payments_offer', 'payments', ['offer_id'], unique=False)
    op.create_index('ix_payments_provider_id', 'payments', ['provider_payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_provider_id', table_name='payments')
    op.drop_index('ix_payments_offer', table_name='payments')
    op.drop_table('payments')
    op.drop_index('ix_offer_events_offer', table_name='offer_events')
    op.drop_table('offer_events')
    op.drop_index('ix_email_log_created', table_name='email_log')
    op.drop_table('email_log')
    op.drop_table('competitor_comparisons')
    op.drop_index('ix_customer_offers_request', table_name='customer_offers')
    op.drop_table('customer_offers')
    op.drop_index('ix_hotel_rooms_hotel_id', table_name='hotel_rooms')
    op.drop_table('hotel_rooms')
    op.drop_index('ix_hotel_offers_lookup', table_name='hotel_offers')
    op.drop_index('ix_hotel_offers_expires', table_name='hotel_offers')
    op.drop_table('hotel_offers')
    op.drop_index('ix_hotel_offer_requests_status_created', table_name='hotel_offer_requests')
    op.drop_table('hotel_offer_requests')
    op.drop_index('ix_search_events_event_created', table_name='search_events')
    op.drop_table('search_events')
    op.drop_table('hotel_providers')
    # ### end Alembic commands ###
